# Generated by Django 4.1.5 on 2024-10-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
